
import { Order } from "../../../lib/mockData";

// Mock de órdenes pendientes para Orders
export const mockOrdersData: Order[] = [
    {
        id: "ORD-1001",
        configuration: "hibrido",
        status: "pending",
        routeId: "RUT-001",
        priority: "critical", // Prioridad crítica
        compartments: [
            {
                id: "comp-001",
                productId: "PROD-001",
                thermalProfileId: "PT-001",
                weight: "8",
            },
            {
                id: "comp-002",
                productId: "PROD-003",
                thermalProfileId: "PT-003",
                weight: "4",
            },
        ],
        expectedDate: "2024-02-04", // Hoy - TTL 90min
        expectedTime: "16:00",
        timeWindow: "hora-especifica",
        notes: "Carga híbrida: Pollo refrigerado y productos secos",
        vehicleId: "VEH-001",
        unit: "TRK-1024",
        trailer: "TRL-5001",
        plate: "RMQ-456",
        driver: "Michael Johnson",
        carrier: "TransFrío Santa Cruz",
        unitStatus: "En Ruta",
        hasActiveTrip: true,
    },
    {
        id: "ORD-1002",
        configuration: "standard",
        status: "accepted", // Estado aceptado
        routeId: "RUT-003",
        priority: "high", // Prioridad alta
        productId: "PROD-004",
        thermalProfileId: "PT-002",
        weight: "8",
        quantity: "80",
        expectedDate: "2024-02-05", // Mañana - TTL 24h
        expectedTime: "10:30",
        timeWindow: "manana",
        notes: "Productos procesados congelados - Ruta con parada en Hospital Japonés",
        vehicleId: "VEH-002",
        unit: "TRK-2051",
        trailer: "TRL-5002",
        plate: "RMQ-789",
        driver: "Sarah Williams",
        carrier: "Logística del Oriente",
        unitStatus: "En Planta",
        hasActiveTrip: false,
    },
    {
        id: "ORD-1003",
        configuration: "standard",
        status: "rejected", // Estado rechazado
        routeId: "RUT-004",
        productId: "PROD-003",
        thermalProfileId: "PT-003",
        weight: "15",
        quantity: "150",
        expectedDate: "2024-02-06", // En 2 días - TTL 24h
        expectedTime: "14:00",
        timeWindow: "tarde",
        notes: "Productos secos sin refrigeración - Ruta con parada en Planta Sofía",
        vehicleId: "VEH-003",
        unit: "TRK-6234",
        trailer: "RMQ-123",
        plate: "RMQ-123",
        driver: "Emma Davis",
        carrier: "Andino Cold Express",
        unitStatus: "Detenido",
        hasActiveTrip: true,
    },
    {
        id: "ORD-1004",
        configuration: "standard",
        status: "pending",
        routeId: "RUT-005",
        productId: "PROD-002",
        thermalProfileId: "PT-001",
        weight: "10",
        quantity: "100",
        expectedDate: "2024-02-08", // En 4 días - TTL 48h
        expectedTime: "09:00",
        timeWindow: "manana",
        notes: "Embutidos refrigerados - Ruta con 2 paradas intermedias",
        vehicleId: "VEH-001",
        unit: "TRK-1024",
        trailer: "TRL-5001",
        plate: "RMQ-456",
        driver: "Michael Johnson",
        carrier: "TransFrío Santa Cruz",
        unitStatus: "Offline",
        hasActiveTrip: false,
    },
    {
        id: "ORD-1005",
        configuration: "hibrido",
        status: "observed", // Estado observado
        routeId: "RUT-005",
        compartments: [
            {
                id: "comp-003",
                productId: "PROD-001",
                thermalProfileId: "PT-001",
                weight: "6",
            },
            {
                id: "comp-004",
                productId: "PROD-004",
                thermalProfileId: "PT-002",
                weight: "5",
            },
        ],
        expectedDate: "2024-02-10", // En 6 días - TTL 48h
        expectedTime: "15:00",
        timeWindow: "tarde",
        notes: "Carga híbrida - Ruta larga con múltiples paradas (vista condensada)",
        vehicleId: "VEH-004",
        unit: "TRK-3456",
        trailer: "TRL-6789",
        plate: "ABC-123",
        driver: "Carlos Mendoza",
        carrier: "FrostLine Bolivia",
        unitStatus: "En Ruta",
        hasActiveTrip: true,
    },
    {
        id: "ORD-1006",
        configuration: "standard",
        status: "dispatched", // Estado despachado
        routeId: "RUT-001",
        productId: "PROD-001",
        thermalProfileId: "PT-001",
        weight: "12",
        quantity: "120",
        expectedDate: "2024-02-12", // En 8 días - TTL 72h
        expectedTime: "11:00",
        timeWindow: "manana",
        notes: "Pollo refrigerado - Orden despachada",
        unit: "TRK-7890",
        trailer: "TRL-1234",
        driver: "Ana García",
        carrier: "TransFrío Santa Cruz",
        unitStatus: "En Ruta",
        hasActiveTrip: true,
    },
    {
        id: "ORD-1007",
        configuration: "standard",
        status: "pending",
        routeId: "RUT-002",
        productId: "PROD-002",
        thermalProfileId: "PT-002",
        weight: "7",
        quantity: "70",
        expectedDate: "2024-02-05", // Mañana - TTL 24h (no vencido)
        expectedTime: "08:00",
        timeWindow: "manana",
        notes: "Embutidos congelados - TTL activo",
        unit: "TRK-5555",
        driver: "Pedro López",
        carrier: "Logística del Oriente",
        unitStatus: "En Planta",
        hasActiveTrip: false,
    },
    {
        id: "ORD-1008",
        configuration: "standard",
        status: "fail_after_accept", // Estado falla post-aceptación
        routeId: "RUT-003",
        productId: "PROD-001",
        thermalProfileId: "PT-001",
        weight: "10",
        quantity: "100",
        expectedDate: "2024-02-05", // Mañana
        expectedTime: "14:00",
        timeWindow: "tarde",
        notes: "vehicle_breakdown: Avería del vehículo en ruta",
        unit: "TRK-8888",
        trailer: "TRL-9999",
        driver: "Roberto Sánchez",
        carrier: "Andino Cold Express",
        unitStatus: "Detenido",
        hasActiveTrip: false,
    },
];
